import type { Metadata } from "next";
import { Geist, Manrope } from "next/font/google";
import localFont from "next/font/local";
import Providers from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const otomanopee = localFont({
  src: "../public/fonts/otomanopee/OtomanopeeOne-Regular.ttf",
  variable: "--font-otomanopee",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${manrope.variable} ${otomanopee.className} antialiased`}
      >
        {/* 
          👇 Providers should include ThemeProvider from next-themes.
          Example:
          export default function Providers({ children }) {
            return (
              <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
                {children}
              </ThemeProvider>
            );
          }
        */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
